### ISSUE TITLE
Random crashes at program end

### ISSUE THREAD

**Issue by baztian** [jpype-project/jpype#765]
I'm facing random crashes at about 30% of my test runs on Python 3.5. Sometimes all my unit tests for my library that uses JPype 0.7.5 pass and the interpreter exits gracefully sometimes they pass but the interpreter crashes with

    Ran 13 tests in 1.807s

    OK

    FATAL: exception not rethrown

    ERROR: InvocationError for command /home/travis/build/baztian/jaydebeapi/.tox/py35-driver-mock-newjpype/bin/coverage run -a --source jaydebeapi test/testsuite.py test_mock (exited with code -6 (SIGIOT)) (exited with code -6)

See https://travis-ci.org/github/baztian/jaydebeapi/jobs/694406619#L383 as an example. I can reproduce the same error on my local machine with tox or via running `python test/testsuite.py test_mock.MockTest` directly.

Sadly I was unable to write a more minimalistic example without all the boilerplate of my library.

Don't know if this is related to #672

**Comment by Thrameos** [comment]
Researching the issue I see the source of the problem is a canceled thread.

https://groups.google.com/forum/#!topic/comp.programming.threads/ZSvPGG-79pc

Now the question is which thread and how.

**Comment by baztian** [comment]
I've set up the build for the jpype master branch. https://github.com/baztian/jaydebeapi/pull/149
At least the first time it ran ok

**Comment by baztian** [comment]
I can't reproduce the issue with the master branch. Everything looks fine to me on travis. But for some reason I'm facing a strange error message in my local tox run

    test_sql_exception_on_rollback (test_mock.MockTest) ... ok

    ----------------------------------------------------------------------
    Ran 13 tests in 0.483s

    OK
    Exception ignored in: <bound method Cursor._close_last of <jaydebeapi.Cursor object at 0x7f4c9c0023c8>>
    Traceback (most recent call last):
    File "/home/bbowe/Sources/jaydebeapi/jaydebeapi/__init__.py", line 515, in _close_last
        self._prep.close()
    RuntimeError: Java Virtual Machine is not running

    Exception ignored in: <bound method Cursor._close_last of <jaydebeapi.Cursor object at 0x7f4c9c0027f0>>
    Traceback (most recent call last):
    File "/home/bbowe/Sources/jaydebeapi/jaydebeapi/__init__.py", line 515, in _close_last
        self._prep.close()
    RuntimeError: Java Virtual Machine is not running

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

Python 3.6.10, Python 3.7.7 and Python 3.8.3

No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya

**Comment by Thrameos** [comment]
The newest version of JPype closes down the JVM before exiting.   There are race conditions in which the JVM closes down and an ``__exit__`` cleanup calls a JVM method after closes.  In general if something is called on clean up use an ``if jpype,isJVMStarted()`` block to avoid unnecessary exceptions,

**Comment by Thrameos** [comment]
Seems like this issue is cleaned up in the release candidate.   Thanks for the bug report and followup checking.   

It was one of the longest outstanding bugs that the original JPype code was not able to shut down the JVM properly due a misunderstanding of the shutdown procedure.  So instead it was calling terminate which left resources dangling and could cause random crashes depending on the order of operations.   When I corrected the shutdown issue, it exposed a lot of bugs in code that was not properly disconnecting threads and the like.    I still have two reports of edge cases (celery and kotlin) that are still triggering race conditions.  Unfortunately neither of them currently replicate for me, but I can't hold of the release for bugs that can't be reproduced.

**Comment by Thrameos** [comment]
```
import jpype
import jpype.imports
jpype.startJVM()
import java

try:
    print("Python")
    print("======")
    raise RuntimeError("foo")
except Exception as ex:
    print(ex)
    print(str(ex))
    print(repr(ex))
    print(type(ex))
    print(type(ex))

print()

try:
    print("Java")
    print("======")
    raise java.lang.RuntimeException("foo")
except Exception as ex:
    print(ex)
    print(str(ex))
    print(repr(ex))
    print(type(ex))
    print(ex.toString())
```

Test case... gives.
```
Python
======
foo
foo
RuntimeError('foo')
<class 'RuntimeError'>
<class 'RuntimeError'>

Java
======
foo
foo
RuntimeException('foo')
<java class 'java.lang.RuntimeException'>
java.lang.RuntimeException: foo
```

I believe your issue is that the ``str()`` method and ``toString()`` don't match.  The question is what is correct in this case.   Should it match Python behavior or should it take Java like behavior on ``str()``?

**Comment by Thrameos** [comment]
I investigated further.  It appears that something is overriding the Java ``str()`` that I installed so I will have to reintroduce it at another level.  The old behavior is now restored in the "named" PR.

**Comment by baztian** [comment]
@Thrameos  you merged that "named" PR into master, right? The tests are still failing. I can't say what is the correct behaviour. But that change would incur a backwards incompatibility.

**Comment by Thrameos** [comment]
Sorry it is in "coverage" which is working towards the release candidate  and on the Thrameos "named" branch as well.

**Comment by baztian** [comment]
The Thrameos named and coverage branches give me a ` Java Virtual Machine is not running` again.

**Comment by Thrameos** [comment]
I would need further information on what is being called.

**Comment by baztian** [comment]
Well that is not that easy to tell especially because it's been a long time I wrote that code. What I can tell though is that [a destructor](https://github.com/baztian/jaydebeapi/blob/jpype-issue-765/jaydebeapi/__init__.py#L522) seems to be involved.
The two test cases that cause the error are

    test_mock.MockTest.test_runtime_exception_on_execute
    test_mock.MockTest.test_sql_exception_on_execute

https://github.com/baztian/jaydebeapi/blob/jpype-issue-765/test/test_mock.py

What's special to them in comparison to the others is that they have a JDBC result set and a prepared statement open and the `__del__` tries to close it.

I already have a improved JayDeBeApi version in place that should not suffer from the issue. https://github.com/baztian/jaydebeapi/pull/150 But still I think it would be nice if JPype would not have these issues.

**Comment by Thrameos** [comment]
This is a general issue with finalizers in garbage collected languages.  You have no way of knowing when a destructor will be called.  When Python shuts down at the end of execution there are a number of race conditions.  In the old version of JPype it would not shutdown the JVM and just terminated the process out from under it unless the user called shutdown.   Calling a Java method after shutdown will always return an exception.

It is nothing peculiar with JPype, as you can get this same bug whenever the resource may be closed before the destructor is called.   Python finalizers must always check the resource is still alive before calling and eat any exceptions that result.  With JPype you should always check if the JVM is currently running or use a try except block to eat the JVM is shutdown exception.   

Currently it throws RuntimeError when you try to use the JVM without a running JVM.   I guess I should make a special exception like ``JVMNotRunning`` that derives from RuntimeError so that it is more clear.
```
    def __del__(self):
        try:
            self._close()
        except RuntimeError:  # pragma: no cover
            pass
```

For much that same reason that Java finalize is deprecated the behavior of ``__del__`` is pretty much unsafe and requires care to use properly.

**Comment by Thrameos** [comment]
@marscher Should I make a special exception type (derived from RuntimeError) for using the JVM when not running so that it is easy to separate JVM errors from other types before the next major release?   I know that we want to code freeze, but there are always a few stray things that people find in testing that would be good to have.

**Comment by marscher** [comment]
Specialized exceptions sound good to me.

**Comment by Thrameos** [comment]
Done with the specialization.

**Comment by baztian** [comment]
Looks good to me

    Exception ignored in: <bound method Cursor._close_last of <jaydebeapi.Cursor object at 0x7fcc3c0cc080>>
    Traceback (most recent call last):
    File "/home/bbowe/Sources/jaydebeapi/jaydebeapi/__init__.py", line 515, in _close_last
        self._prep.close()
    jpype._core.JVMNotRunning: Java Virtual Machine is not running

I can live with that as I've changed the behaviour for my project to not use destructors anymore and delegate the responsibility to closing connections to the users. Thank!

**Comment by marscher** [comment]
There are no real destructors in Python anyway. Thanks for testing.
