### ISSUE TITLE
Java14: DynamicClassLoader api failure

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#865]
With JPype-1.1.0 and OpenJDK-14 I observe the following:
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpype
>>> jpype.startJVM()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marscher/miniconda3/lib/python3.8/site-packages/jpype/_core.py", line 215, in startJVM
    _jpype.startup(jvmpath, tuple(args),
SystemError: java.lang.ClassNotFoundException: org.jpype.classloader.DynamicClassLoader
```
```
$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12)
OpenJDK 64-Bit Server VM (build 14.0.2+12, mixed mode)
```

**Comment by marscher** [comment]
Eventually we should extend our (already large) test matrix to include several (commonly used) JDKs?

**Comment by marscher** [comment]
Mhm, actually this seems to be an error with a missing jpype.jar, not Java14

**Comment by marscher** [comment]
I just invoked setup.py sdist as usual, then performed a pip installation with the distribution archive.

**Comment by Thrameos** [comment]
Darn sounds like I will need to do another patch release.   org.jpype.jar should be in all of the wheels and get picked up by the boot loader.   But this is the first time that we distributed something which uses that process so there may be some unexpected problems.

The key problem for testing alternative JDK is simply the availability of those JDK on the continuous integration system.  Often it seems that they have only one JDK available or the process or switched between them is error prone in terms of paths.   I pushed through some feature requests on azure but I haven't tried to see how well they work.   My last attempt was unsuccessful as the paths only updated on the first select in the process.  I was considering making a pipeline that constructs a big artifact with a whole bunch of different JDK versions which may be another solution.   Installing JDK multiple times is pretty time consuming, but perhaps if we can reuse it may be reasonable.

The only issue that I am aware of is some versions of Java or Python are truncating the name of the import resulting in fails to load.  There is an issue on it, but thus far I have not been able to replicate it, so I am not sure if the Java version or the Python version (or something else) that is doing the truncation.

**Comment by pelson** [comment]
Confirmed the same problem on Linux both openjdk 8 & 11, Python 3.8 (untested other Py versions). 
Master still continues to perform beautifully though, so it is definitely a packaging problem.

**Comment by ikus060** [comment]
Same here, issue with the latest JPype version 1.1.0. I don't have any issue if I revert back to 1.0.2.

**Comment by Thrameos** [comment]
I looked at the issue.  The wheels are definitely missing files that are present in the bdist version.   No clue as to why that would be.

**Comment by marscher** [comment]
We should sort this out asap, as I already pushed those broken wheels to pypi. I guess we should go for a micro release then. Thanks for looking into it.

**Comment by Thrameos** [comment]
Not to worry I have the release system recreating the issue right now.   Looks like it was a problem in the pip install build path.   Not sure why it didn't produce an error but I have a fix that is being tested on release right now.

**Comment by Thrameos** [comment]
@marscher is there any way to remove the linux files from the 1.1.0 release as they are incomplete?  I finish the 1.1.1 release with completed files shortly, but it would be good to kill the bad files so they don't propagate.

**Comment by marscher** [comment]
I can remove the wheel files, but the release has to keep at least one file to distribute. As the source tarball also contains the jar packaging bug, I suspect, we will end up deleting the whole release. There is the option to "yank" the release, which means that pip installations will get displayed a message, but most likely people will not notice it. So I'm in favor of deleting in the meantime.

**Comment by Thrameos** [comment]
Okay I pushed the corrected micro release.   I checked that the missing file is included, but don't have a good way to check beyond that.   I recommend deleting the 1.1.0 release from PyPi and then just creating a 1.1.1 with the release notes from 1.1.0 as we don't want to reference a release which is not available.  Sounds like a plan?

**Comment by marscher** [comment]
We should also change the matrix to pip install the current tree and then test against this installation to circumvent such mistakes.

**Comment by Thrameos** [comment]
Yeah it likely should be part of the matrix through I am not quite sure how we would pull it off.   I suppose a special copy of the windows image could build from scratch and build from pip and compare the two distributions.   Unfortunately the linux build is a docker and lacks a JVM so we can't actually test the resulting wheel currently.

**Comment by marscher** [comment]
We should also change the matrix to pip install the current tree and then test against this installation to circumvent such mistakes.

**Comment by marscher** [comment]
I think the error arises from the fact, that we are using an Extension class to distribute the jar. When looking into the debugger, the output filename for the java extension is something like "org/jpype.cpython-37m-x86_64-linux-gnu.so", which does not exists of course. We should just ship the jar file with the usual distutils mechanism to ship non-pythonic files and ensure that the jar is always being build, when build_ext or sdist is invoked.

**Comment by marscher** [comment]
Lets postpone bleeding edge Python3.9 until we have a working 1.1.0 for the older snakes.

**Comment by Thrameos** [comment]
The extension process should work as far as I am aware.  The problem was simply the jar cache did not place into the same location as the extension was intending so it didn't get shipped off.  I tried having the extension create the jar in a generic location but it just can't happen because of how the distutils works.   Note that we will need the extension to create pyc files in the jar eventually as well as a way for third parties to make their own shippable jars.   I suppose we can make our own extension process rather than hijacking the extension process, but this really shouldn't be much different other compilation processes.

The part I haven't bit off it when we start compiling in versioned python files we will need to have the jar file name specific to the python version it contains.  The process isn't going to be horrible, as we will simply have the jar cache use tar to unpack the cached jar into the build location and then add the specific patterns and then use ta r to rebuild the jar file without the need for the jdk.  I wish pyc files were able to work cross version or had some way of creating stable API versions.  

The other hang ups I see is we are going to start distribution the ASM library and other jar files that are needed for the process especially when I get epypj stuff working.  This also back links into python dynamic link library.   Unfortunately the stable python API doesn't cover a lot of our uses and I badly need them to add some hooks so that the situation gets better, but all my requests for help on forums have been given no response.

**Comment by Thrameos** [comment]
@marscher I believe the 1.1.1 files are all on the release page.   Can you check them over and delete the 1.1.0 release?

**Comment by marscher** [comment]
I already deleted the 1.1.0. Will upload the patch release asap. Thank you so much!

**Comment by marscher** [comment]
fixed by #867
